services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:cuda12-latest
    ports:
      - 8888:8888
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=0